name: Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: Cypress
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v1
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
